/*
 * AudioHotkeys.cs
 * Created by Lautaro Dichio (ldichio.com.ar) | Unity + Wwise Tools
 * 
 * PURPOSE
 * Demo component to quickly test `AKLD_SOTemplate` assets in Play Mode.
 * It maps keyboard keys to autogenerated methods, allowing you to verify 
 * Events, States, Switches, and RTPCs without writing custom scripts.
 * 
 * WHY
 * - 🧪 For prototyping: instantly check if your template setup works.  
 * - 🧑‍💻 For programmers: see how the autocompletion system is used in code.  
 * - 🎚️ For audio teams: validate that Events/States/RTPCs are firing correctly.  
 * 
 * HOW
 * Attach this script to any GameObject, assign an `AKLD_SOTemplate` in the Inspector, 
 * and press keys during Play Mode:
 * - **1 2 3 4** → Trigger example Events (EventNumber1–4)  
 * - **Q W E R** → Switch music layers via States (Layer1–4)  
 * - **M** → Post the Music event  
 * - **A S D** → Adjust the MusicValue RTPC (global volume)  
 *   - A = 100 (loud)  
 *   - S = 50 (medium)  
 *   - D = 10 (quiet)  
 * 
 * NOTE
 * This script is intended only as a **demo harness** for testing 
 * and should not be used in production builds.
 */



using UnityEngine;

public class AudioHotkeys : MonoBehaviour
{
    [SerializeField] private AKLD_SOTemplate audioTest;


    private void Start()
    {
        audioTest.Layer1(gameObject);
        audioTest.MusicValue(gameObject, 75f);
       
    }

    void Update()
    {
        //Event

        if (Input.GetKeyDown(KeyCode.Alpha1))
            audioTest.EventNumber1(gameObject);


        if (Input.GetKeyDown(KeyCode.Alpha2))
            audioTest.EventNumber2(gameObject);

        if (Input.GetKeyDown(KeyCode.Alpha3))
            audioTest.EventNumber3(gameObject);

        if (Input.GetKeyDown(KeyCode.Alpha4))
            audioTest.EventNumber4(gameObject);

        if (Input.GetKeyDown(KeyCode.M))
            audioTest.Music(this.gameObject);
      


        //STATE
        if (Input.GetKeyDown(KeyCode.Q))
            audioTest.Layer1(gameObject);

        if (Input.GetKeyDown(KeyCode.W))
            audioTest.Layer2(gameObject);

        if (Input.GetKeyDown(KeyCode.E))
            audioTest.Layer3(gameObject);

        if (Input.GetKeyDown(KeyCode.R))
            audioTest.Layer4(gameObject);


        //RTPC

        if (Input.GetKeyDown(KeyCode.A))
            audioTest.MusicValue(this.gameObject, 100);

        if (Input.GetKeyDown(KeyCode.S))
            audioTest.MusicValue(this.gameObject, 50);


        if (Input.GetKeyDown(KeyCode.D))
        {
            audioTest.MusicValue(this.gameObject, 10);
            Debug.Log("volumen a 10");
        }
    }
}
